=== DeadOrLife/webservice01/src/com/wz/service/xml/schema/02.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/02"
        xmlns:tns="http://www.example.org/02"
        elementFormDefault="qualified">
    <element name="books">
        <complexType>
            <sequence minOccurs="1" maxOccurs="unbounded">
                <element name="book">
                    <complexType>
                        <sequence>
                            <element name="title" type="string"/>
                            <element name="content" type="string"/>
                            <choice>
                                <element name="author" type="string"/>
                                <!--复杂类型-->
                                <element name="authors">
                                    <complexType>
                                        <sequence minOccurs="1" maxOccurs="unbounded">
                                            <element name="author" type="string"></element>
                                        </sequence>
                                    </complexType>
                                </element>
                            </choice>
                            <element name="price" type="double"/>
                        </sequence>
                        <attribute name="id" type="int" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== DeadOrLife/webservice01/out/production/webservice01/com/wz/service/xml/schema/02_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<book:books xmlns:book="http://www.example.org/02"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="02.xsd">
    <book:book id="1">
        <book:title>程序员的自我修养</book:title>
        <book:content>寂寞与孤独</book:content>
        <book:author>wz</book:author>
        <book:price>2.2</book:price>
    </book:book>
    <book:book id="2">
        <book:title>javascript</book:title>
        <book:content>入门到精通</book:content>
        <book:authors>
            <book:author>Make</book:author>
            <book:author>Jerry</book:author>
        </book:authors>
        <book:price>3.3</book:price>
    </book:book>
</book:books>
