=== DeadOrLife/webservice01/src/com/wz/service/xml/dtd/classroom.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--,隔开也要注意顺序-->
<!ELEMENT classroom (grade,claName,students)>
<!ATTLIST classroom id ID #REQUIRED>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT claName (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (id,name,age)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!--?0次或者1次 *0次多次 +1次或者多次 不写1次-->

=== DeadOrLife/webservice01/out/production/webservice01/com/wz/service/xml/dtd/classroom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classroom SYSTEM "classroom.dtd">
<classroom id="p1">
    <grade>2015</grade>
    <claName>计算机应用技术</claName>
    <students>
        <student>
            <id>1</id>
            <name>wz</name>
            <age>24</age>
        </student>
    </students>
</classroom>
